mode: deployment

image:
  repository: "otel/opentelemetry-collector"
  tag: "0.84.0"


# Config de receivers, processors y exporters
config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  processors:
    batch:

  exporters:
    otlp:
      endpoint: "http://jaeger-collector:4317" #endpoint del jeager dentro de mi cluster
      insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
